name: Node.js CI
'on':
  push:
    branches:
      - master
      - beta
      - renovate/**
  pull_request:
    types:
      - opened
      - synchronize
env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm clean-install
      - run: npm test
  trigger-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: []
    steps:
      - uses: octokit/request-action@v2.x
        with:
          route: >-
            POST
            /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
          owner: pragmatic-divops
          repo: eslint-config-react
          ref: ${{ github.ref }}
          workflow_id: release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
